services:
  db:
    image: postgres:18-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
        - ./init-scripts:/docker-entrypoint-initdb.d:ro
    ports:
       - "15432:5432"
  web:
    build: .
    command: python ./main.py
    ports:
      - "8000:8000"
    environment:
        DB_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
        DB_USER: "${DB_USER}"
        DB_PASSWORD: "${DB_PASSWORD}"
        DB_NAME: "${DB_NAME}"
    restart: always